/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MinhasComprasRouteImport } from './routes/minhas-compras'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CheckoutPlanIdRouteImport } from './routes/checkout.$planId'
import { Route as ApiPublicIntrospectHyroRouteImport } from './routes/api/public/introspect-hyro'

const MinhasComprasRoute = MinhasComprasRouteImport.update({
  id: '/minhas-compras',
  path: '/minhas-compras',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutPlanIdRoute = CheckoutPlanIdRouteImport.update({
  id: '/checkout/$planId',
  path: '/checkout/$planId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicIntrospectHyroRoute = ApiPublicIntrospectHyroRouteImport.update({
  id: '/api/public/introspect-hyro',
  path: '/api/public/introspect-hyro',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/minhas-compras': typeof MinhasComprasRoute
  '/checkout/$planId': typeof CheckoutPlanIdRoute
  '/api/public/introspect-hyro': typeof ApiPublicIntrospectHyroRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/minhas-compras': typeof MinhasComprasRoute
  '/checkout/$planId': typeof CheckoutPlanIdRoute
  '/api/public/introspect-hyro': typeof ApiPublicIntrospectHyroRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/minhas-compras': typeof MinhasComprasRoute
  '/checkout/$planId': typeof CheckoutPlanIdRoute
  '/api/public/introspect-hyro': typeof ApiPublicIntrospectHyroRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/minhas-compras'
    | '/checkout/$planId'
    | '/api/public/introspect-hyro'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/minhas-compras'
    | '/checkout/$planId'
    | '/api/public/introspect-hyro'
  id:
    | '__root__'
    | '/'
    | '/minhas-compras'
    | '/checkout/$planId'
    | '/api/public/introspect-hyro'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MinhasComprasRoute: typeof MinhasComprasRoute
  CheckoutPlanIdRoute: typeof CheckoutPlanIdRoute
  ApiPublicIntrospectHyroRoute: typeof ApiPublicIntrospectHyroRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/minhas-compras': {
      id: '/minhas-compras'
      path: '/minhas-compras'
      fullPath: '/minhas-compras'
      preLoaderRoute: typeof MinhasComprasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/$planId': {
      id: '/checkout/$planId'
      path: '/checkout/$planId'
      fullPath: '/checkout/$planId'
      preLoaderRoute: typeof CheckoutPlanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/introspect-hyro': {
      id: '/api/public/introspect-hyro'
      path: '/api/public/introspect-hyro'
      fullPath: '/api/public/introspect-hyro'
      preLoaderRoute: typeof ApiPublicIntrospectHyroRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MinhasComprasRoute: MinhasComprasRoute,
  CheckoutPlanIdRoute: CheckoutPlanIdRoute,
  ApiPublicIntrospectHyroRoute: ApiPublicIntrospectHyroRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
